# Generated by Django
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.EmailField(unique=True, max_length=150, verbose_name='E-mail Acadêmico')),
                ('password_hash', models.TextField(verbose_name='Senha Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Alunos (Estudante)',
                'verbose_name_plural': '1. Cadastro de Alunos',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, verbose_name='ID do Aluno')),
                ('data', models.JSONField(verbose_name='Conteúdo de Estudo (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sintetizado em')),
            ],
            options={
                'verbose_name': 'Módulo de Estudo',
                'verbose_name_plural': '2. Módulos de Estudo (AI)',
                'db_table': 'lectures',
            },
        ),
    ]
