# Generated by Django 5.2.15 on 2026-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_new_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardmanual',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo: '),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo: '),
        ),
    ]
